INSERT INTO skill (name, proficiency, type) VALUES
    ('C', 7, 1),
    ('C++', 8, 1),
    ('Elixir', 6, 1),
    ('Java', 10, 1),
    ('Python', 7, 1),
    ('MySQL', 9, 2),
    ('Oracle', 7, 2),
    ('PostgreSQL', 7, 2),
    ('Bootstrap', 10, 3),
    ('jQuery', 9, 3),
    ('Phoenix', 7, 3),
    ('React', 10, 3),
    ('Redux', 6, 3),
    ('Spring', 7, 3),
    ('Git', 9, 4),
    ('Jenkins', 8, 4),
    ('Subversion', 10, 4),
    ('macOS', 10, 5),
    ('Windows', 10, 5),
    ('CSS', 10, 6),
    ('HTML5', 10, 6),
    ('JavaScript', 10, 6),
    ('Rest API', 9, 6);